/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entities._Account;

/**
 *
 * @author ICHIGEKI
 */
public class GDAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FAdmin
     */
    public GDAdmin() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRoomManage = new javax.swing.JButton();
        btnServiceManage = new javax.swing.JButton();
        btnEmployeeManage = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnAccountManage = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aaaaaaaaaaaaaaaaaaaa.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("PHẦN MỀM QUẢN LÝ KHÁCH SẠN     ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("GIAO DIỆN ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(824, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnRoomManage.setBackground(new java.awt.Color(255, 153, 153));
        btnRoomManage.setText("QUẢN LÝ PHÒNG");
        btnRoomManage.setMaximumSize(new java.awt.Dimension(230, 100));
        btnRoomManage.setMinimumSize(new java.awt.Dimension(230, 100));
        btnRoomManage.setPreferredSize(new java.awt.Dimension(230, 100));
        btnRoomManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomManageActionPerformed(evt);
            }
        });

        btnServiceManage.setBackground(new java.awt.Color(255, 153, 204));
        btnServiceManage.setText("DỊCH VỤ");
        btnServiceManage.setMaximumSize(new java.awt.Dimension(230, 100));
        btnServiceManage.setMinimumSize(new java.awt.Dimension(230, 100));
        btnServiceManage.setPreferredSize(new java.awt.Dimension(230, 100));
        btnServiceManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceManageActionPerformed(evt);
            }
        });

        btnEmployeeManage.setBackground(new java.awt.Color(255, 153, 102));
        btnEmployeeManage.setText("QUẢN LÝ NHÂN VIÊN");
        btnEmployeeManage.setMaximumSize(new java.awt.Dimension(230, 100));
        btnEmployeeManage.setMinimumSize(new java.awt.Dimension(230, 100));
        btnEmployeeManage.setPreferredSize(new java.awt.Dimension(230, 100));
        btnEmployeeManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeManageActionPerformed(evt);
            }
        });

        btnChangePass.setBackground(new java.awt.Color(0, 255, 255));
        btnChangePass.setText("ĐỔI MẬT KHẨU");
        btnChangePass.setMaximumSize(new java.awt.Dimension(230, 100));
        btnChangePass.setMinimumSize(new java.awt.Dimension(230, 100));
        btnChangePass.setPreferredSize(new java.awt.Dimension(230, 100));
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        btnAccountManage.setBackground(new java.awt.Color(255, 255, 153));
        btnAccountManage.setText("QUẢN LÝ TÀI KHOẢN");
        btnAccountManage.setMaximumSize(new java.awt.Dimension(230, 100));
        btnAccountManage.setMinimumSize(new java.awt.Dimension(230, 100));
        btnAccountManage.setPreferredSize(new java.awt.Dimension(230, 100));
        btnAccountManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountManageActionPerformed(evt);
            }
        });

        btnLogout.setText("ĐĂNG XUẤT");
        btnLogout.setMaximumSize(new java.awt.Dimension(230, 100));
        btnLogout.setMinimumSize(new java.awt.Dimension(230, 100));
        btnLogout.setPreferredSize(new java.awt.Dimension(230, 100));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAccountManage, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoomManage, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnServiceManage, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmployeeManage, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServiceManage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRoomManage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployeeManage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAccountManage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomManageActionPerformed
        Phong aa = new Phong();
        aa.setAccount(acc);
        aa.setLocationRelativeTo(this);
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRoomManageActionPerformed

    private void btnServiceManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceManageActionPerformed
        FAService r = new FAService();
        r.setAccount(acc);
        r.setLocationRelativeTo(this);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiceManageActionPerformed

    private void btnEmployeeManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeManageActionPerformed
        NhanVien ff = new NhanVien();
        ff.setAccount(acc);
        ff.setLocationRelativeTo(this);
        ff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmployeeManageActionPerformed

    private void btnAccountManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountManageActionPerformed
        TaiKhoan acc = new TaiKhoan();
        acc.setAccount(this.acc);
        acc.setLocationRelativeTo(this);
        acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountManageActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        DoiMatKhau change = new DoiMatKhau(acc.getUserName());
        change.setAccount(acc);
        change.setLocationRelativeTo(this);
        change.setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login logout = new Login();
        logout.setLocationRelativeTo(this);
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountManage;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnEmployeeManage;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRoomManage;
    private javax.swing.JButton btnServiceManage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    _Account acc = new _Account();

    public void setAccount(_Account aa) {
        acc = aa;
    }
}
